---
title: Hello!
author: The dexter makers
date: '2017-12-13'
slug: hello
categories:
  - R
  - Psychometrics
tags:
  - dexter Cito
---

# About dexter, Cito, and this blog

[Cito](http://www.cito.nl) is a Dutch educational testing company founded about 50 years ago and situated in [Arnhem](https://en.wikipedia.org/wiki/Arnhem). Cito is responsible for a large part of the educational assessments in the Netherlands, participates in numerous international projects such as PISA or ESLC, and offers consultancy around the globe.

In a somewhat unprecedented move, Cito have decided to publish their latest psychometric software as open source, even before it is completely finished. The R package, __dexter__, has been [available on CRAN](https://CRAN.R-project.org/package=dexter) since February 2017, and is currently at version 0.5.4. 

In this blog, we would like to share news about the software, tutorials, and futher information useful to the users. We might also discuss broader topics in educational assessment and its social impact. The views expressed in the blog are our own. __dexter__ is developed at Cito, the Netherlands, with subsidy from the Dutch Ministry of Education, Culture, and Science.

Timo Bechger • 
Jesse Koops • 
Gunter Maris • 
Ivailo Partchev
