// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// fast_factor
SEXP fast_factor(SEXP x, bool as_int);
RcppExport SEXP _dexter_fast_factor(SEXP xSEXP, SEXP as_intSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type as_int(as_intSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_factor(x, as_int));
    return rcpp_result_gen;
END_RCPP
}
// fast_factor_lev
SEXP fast_factor_lev(SEXP x, SEXP levs, bool as_int);
RcppExport SEXP _dexter_fast_factor_lev(SEXP xSEXP, SEXP levsSEXP, SEXP as_intSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type levs(levsSEXP);
    Rcpp::traits::input_parameter< bool >::type as_int(as_intSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_factor_lev(x, levs, as_int));
    return rcpp_result_gen;
END_RCPP
}
// ppoint
std::string ppoint(SEXP x);
RcppExport SEXP _dexter_ppoint(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ppoint(x));
    return rcpp_result_gen;
END_RCPP
}
// fill_resp_matrix
void fill_resp_matrix(const IntegerVector& person_id, const IntegerVector& item_id, const IntegerVector& item_score, arma::imat& out);
RcppExport SEXP _dexter_fill_resp_matrix(SEXP person_idSEXP, SEXP item_idSEXP, SEXP item_scoreSEXP, SEXP outSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type person_id(person_idSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type item_id(item_idSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type item_score(item_scoreSEXP);
    Rcpp::traits::input_parameter< arma::imat& >::type out(outSEXP);
    fill_resp_matrix(person_id, item_id, item_score, out);
    return R_NilValue;
END_RCPP
}
// ds_connected_groups
IntegerVector ds_connected_groups(const IntegerMatrix& a);
RcppExport SEXP _dexter_ds_connected_groups(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(ds_connected_groups(a));
    return rcpp_result_gen;
END_RCPP
}
// unequal_categories_C
std::vector<int> unequal_categories_C(const IntegerVector& group_id, const IntegerVector& item_id, const IntegerVector& item_score, const int nit, const int max_score);
RcppExport SEXP _dexter_unequal_categories_C(SEXP group_idSEXP, SEXP item_idSEXP, SEXP item_scoreSEXP, SEXP nitSEXP, SEXP max_scoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type group_id(group_idSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type item_id(item_idSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type item_score(item_scoreSEXP);
    Rcpp::traits::input_parameter< const int >::type nit(nitSEXP);
    Rcpp::traits::input_parameter< const int >::type max_score(max_scoreSEXP);
    rcpp_result_gen = Rcpp::wrap(unequal_categories_C(group_id, item_id, item_score, nit, max_score));
    return rcpp_result_gen;
END_RCPP
}
// make_booklets
List make_booklets(const IntegerVector& person_id, const IntegerVector& item_id, const IntegerVector& item_score, IntegerVector& booklet_id, IntegerVector& booklet_score, const bool merged);
RcppExport SEXP _dexter_make_booklets(SEXP person_idSEXP, SEXP item_idSEXP, SEXP item_scoreSEXP, SEXP booklet_idSEXP, SEXP booklet_scoreSEXP, SEXP mergedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type person_id(person_idSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type item_id(item_idSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type item_score(item_scoreSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type booklet_id(booklet_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type booklet_score(booklet_scoreSEXP);
    Rcpp::traits::input_parameter< const bool >::type merged(mergedSEXP);
    rcpp_result_gen = Rcpp::wrap(make_booklets(person_id, item_id, item_score, booklet_id, booklet_score, merged));
    return rcpp_result_gen;
END_RCPP
}
// make_booklets_summed
List make_booklets_summed(IntegerVector& person_id, IntegerVector& booklet_id, IntegerVector& item_id, IntegerVector& item_score, const bool merged);
RcppExport SEXP _dexter_make_booklets_summed(SEXP person_idSEXP, SEXP booklet_idSEXP, SEXP item_idSEXP, SEXP item_scoreSEXP, SEXP mergedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector& >::type person_id(person_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type booklet_id(booklet_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type item_id(item_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type item_score(item_scoreSEXP);
    Rcpp::traits::input_parameter< const bool >::type merged(mergedSEXP);
    rcpp_result_gen = Rcpp::wrap(make_booklets_summed(person_id, booklet_id, item_id, item_score, merged));
    return rcpp_result_gen;
END_RCPP
}
// make_booklets_summed_matrix
List make_booklets_summed_matrix(const IntegerVector& mtx, const int ncol, const int nrow);
RcppExport SEXP _dexter_make_booklets_summed_matrix(SEXP mtxSEXP, SEXP ncolSEXP, SEXP nrowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type mtx(mtxSEXP);
    Rcpp::traits::input_parameter< const int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< const int >::type nrow(nrowSEXP);
    rcpp_result_gen = Rcpp::wrap(make_booklets_summed_matrix(mtx, ncol, nrow));
    return rcpp_result_gen;
END_RCPP
}
// make_booklets_matrix
List make_booklets_matrix(const IntegerVector& mtx, const int ncol, const int nrow);
RcppExport SEXP _dexter_make_booklets_matrix(SEXP mtxSEXP, SEXP ncolSEXP, SEXP nrowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type mtx(mtxSEXP);
    Rcpp::traits::input_parameter< const int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< const int >::type nrow(nrowSEXP);
    rcpp_result_gen = Rcpp::wrap(make_booklets_matrix(mtx, ncol, nrow));
    return rcpp_result_gen;
END_RCPP
}
// mutate_booklet_score
IntegerVector mutate_booklet_score(const IntegerVector& person_id, const IntegerVector& booklet_id, const IntegerVector& item_score);
RcppExport SEXP _dexter_mutate_booklet_score(SEXP person_idSEXP, SEXP booklet_idSEXP, SEXP item_scoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type person_id(person_idSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type booklet_id(booklet_idSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type item_score(item_scoreSEXP);
    rcpp_result_gen = Rcpp::wrap(mutate_booklet_score(person_id, booklet_id, item_score));
    return rcpp_result_gen;
END_RCPP
}
// summarise_booklet_score
int summarise_booklet_score(IntegerVector& person_id, IntegerVector& booklet_id, IntegerVector& item_id, IntegerVector& item_score);
RcppExport SEXP _dexter_summarise_booklet_score(SEXP person_idSEXP, SEXP booklet_idSEXP, SEXP item_idSEXP, SEXP item_scoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector& >::type person_id(person_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type booklet_id(booklet_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type item_id(item_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type item_score(item_scoreSEXP);
    rcpp_result_gen = Rcpp::wrap(summarise_booklet_score(person_id, booklet_id, item_id, item_score));
    return rcpp_result_gen;
END_RCPP
}
// merge_booklets
DataFrame merge_booklets(IntegerVector& booklet_id, const IntegerVector& person_id, const IntegerVector ds_booklet_id, const int maxb);
RcppExport SEXP _dexter_merge_booklets(SEXP booklet_idSEXP, SEXP person_idSEXP, SEXP ds_booklet_idSEXP, SEXP maxbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector& >::type booklet_id(booklet_idSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type person_id(person_idSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type ds_booklet_id(ds_booklet_idSEXP);
    Rcpp::traits::input_parameter< const int >::type maxb(maxbSEXP);
    rcpp_result_gen = Rcpp::wrap(merge_booklets(booklet_id, person_id, ds_booklet_id, maxb));
    return rcpp_result_gen;
END_RCPP
}
// get_design_C
DataFrame get_design_C(const IntegerVector& booklet_id, const IntegerVector& item_id);
RcppExport SEXP _dexter_get_design_C(SEXP booklet_idSEXP, SEXP item_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type booklet_id(booklet_idSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type item_id(item_idSEXP);
    rcpp_result_gen = Rcpp::wrap(get_design_C(booklet_id, item_id));
    return rcpp_result_gen;
END_RCPP
}
// polytomize_C
List polytomize_C(IntegerVector& booklet_id, IntegerVector& person_id, IntegerVector& item_prop, IntegerVector& item_score, IntegerVector& booklet_score, const int nlev, const int nb);
RcppExport SEXP _dexter_polytomize_C(SEXP booklet_idSEXP, SEXP person_idSEXP, SEXP item_propSEXP, SEXP item_scoreSEXP, SEXP booklet_scoreSEXP, SEXP nlevSEXP, SEXP nbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector& >::type booklet_id(booklet_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type person_id(person_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type item_prop(item_propSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type item_score(item_scoreSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type booklet_score(booklet_scoreSEXP);
    Rcpp::traits::input_parameter< const int >::type nlev(nlevSEXP);
    Rcpp::traits::input_parameter< const int >::type nb(nbSEXP);
    rcpp_result_gen = Rcpp::wrap(polytomize_C(booklet_id, person_id, item_prop, item_score, booklet_score, nlev, nb));
    return rcpp_result_gen;
END_RCPP
}
// is_person_booklet_sorted
bool is_person_booklet_sorted(const IntegerVector& booklet_id, const IntegerVector& person_id);
RcppExport SEXP _dexter_is_person_booklet_sorted(SEXP booklet_idSEXP, SEXP person_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type booklet_id(booklet_idSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type person_id(person_idSEXP);
    rcpp_result_gen = Rcpp::wrap(is_person_booklet_sorted(booklet_id, person_id));
    return rcpp_result_gen;
END_RCPP
}
// parms_is_superset_matrix
bool parms_is_superset_matrix(const IntegerMatrix& x, const IntegerVector& item_id, const IntegerVector& item_score, const int maxs);
RcppExport SEXP _dexter_parms_is_superset_matrix(SEXP xSEXP, SEXP item_idSEXP, SEXP item_scoreSEXP, SEXP maxsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type item_id(item_idSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type item_score(item_scoreSEXP);
    Rcpp::traits::input_parameter< const int >::type maxs(maxsSEXP);
    rcpp_result_gen = Rcpp::wrap(parms_is_superset_matrix(x, item_id, item_score, maxs));
    return rcpp_result_gen;
END_RCPP
}
// suf_stats_nrm
List suf_stats_nrm(const IntegerVector& booklet_id, const IntegerVector& booklet_score, const IntegerVector& item_id, const IntegerVector& item_score, const int nit, const int max_score);
RcppExport SEXP _dexter_suf_stats_nrm(SEXP booklet_idSEXP, SEXP booklet_scoreSEXP, SEXP item_idSEXP, SEXP item_scoreSEXP, SEXP nitSEXP, SEXP max_scoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type booklet_id(booklet_idSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type booklet_score(booklet_scoreSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type item_id(item_idSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type item_score(item_scoreSEXP);
    Rcpp::traits::input_parameter< const int >::type nit(nitSEXP);
    Rcpp::traits::input_parameter< const int >::type max_score(max_scoreSEXP);
    rcpp_result_gen = Rcpp::wrap(suf_stats_nrm(booklet_id, booklet_score, item_id, item_score, nit, max_score));
    return rcpp_result_gen;
END_RCPP
}
// suf_stats_im
List suf_stats_im(const IntegerVector& booklet_score, const IntegerVector& item_id, const IntegerVector& item_score, const int nit, const int max_score);
RcppExport SEXP _dexter_suf_stats_im(SEXP booklet_scoreSEXP, SEXP item_idSEXP, SEXP item_scoreSEXP, SEXP nitSEXP, SEXP max_scoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type booklet_score(booklet_scoreSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type item_id(item_idSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type item_score(item_scoreSEXP);
    Rcpp::traits::input_parameter< const int >::type nit(nitSEXP);
    Rcpp::traits::input_parameter< const int >::type max_score(max_scoreSEXP);
    rcpp_result_gen = Rcpp::wrap(suf_stats_im(booklet_score, item_id, item_score, nit, max_score));
    return rcpp_result_gen;
END_RCPP
}
// score_tab_single
IntegerVector score_tab_single(const IntegerVector& scores, const int max_score);
RcppExport SEXP _dexter_score_tab_single(SEXP scoresSEXP, SEXP max_scoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< const int >::type max_score(max_scoreSEXP);
    rcpp_result_gen = Rcpp::wrap(score_tab_single(scores, max_score));
    return rcpp_result_gen;
END_RCPP
}
// tia_C
DataFrame tia_C(const IntegerVector& booklet_id, const IntegerVector& booklet_score, const IntegerVector& item_id, const IntegerVector& item_score, const int nb, const int nit, const IntegerVector& frst_item, const IntegerVector& ds_booklet_id, const IntegerVector& ds_item_id);
RcppExport SEXP _dexter_tia_C(SEXP booklet_idSEXP, SEXP booklet_scoreSEXP, SEXP item_idSEXP, SEXP item_scoreSEXP, SEXP nbSEXP, SEXP nitSEXP, SEXP frst_itemSEXP, SEXP ds_booklet_idSEXP, SEXP ds_item_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type booklet_id(booklet_idSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type booklet_score(booklet_scoreSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type item_id(item_idSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type item_score(item_scoreSEXP);
    Rcpp::traits::input_parameter< const int >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< const int >::type nit(nitSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type frst_item(frst_itemSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type ds_booklet_id(ds_booklet_idSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type ds_item_id(ds_item_idSEXP);
    rcpp_result_gen = Rcpp::wrap(tia_C(booklet_id, booklet_score, item_id, item_score, nb, nit, frst_item, ds_booklet_id, ds_item_id));
    return rcpp_result_gen;
END_RCPP
}
// ElSym_C
void ElSym_C(const arma::vec& b, const arma::ivec& a, const arma::ivec& first, const arma::ivec& last, const int item1, const int item2, const int nI, const int mS, arma::vec& g);
RcppExport SEXP _dexter_ElSym_C(SEXP bSEXP, SEXP aSEXP, SEXP firstSEXP, SEXP lastSEXP, SEXP item1SEXP, SEXP item2SEXP, SEXP nISEXP, SEXP mSSEXP, SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type last(lastSEXP);
    Rcpp::traits::input_parameter< const int >::type item1(item1SEXP);
    Rcpp::traits::input_parameter< const int >::type item2(item2SEXP);
    Rcpp::traits::input_parameter< const int >::type nI(nISEXP);
    Rcpp::traits::input_parameter< const int >::type mS(mSSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type g(gSEXP);
    ElSym_C(b, a, first, last, item1, item2, nI, mS, g);
    return R_NilValue;
END_RCPP
}
// possible_scores_C
arma::ivec possible_scores_C(const arma::ivec& a, const arma::ivec& first, const arma::ivec& last);
RcppExport SEXP _dexter_possible_scores_C(SEXP aSEXP, SEXP firstSEXP, SEXP lastSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::ivec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type last(lastSEXP);
    rcpp_result_gen = Rcpp::wrap(possible_scores_C(a, first, last));
    return rcpp_result_gen;
END_RCPP
}
// ittotmat0_C
arma::mat ittotmat0_C(const arma::vec& b, const arma::ivec& a, const arma::vec& c, const arma::ivec& first, const arma::ivec& last, const arma::ivec& ps);
RcppExport SEXP _dexter_ittotmat0_C(SEXP bSEXP, SEXP aSEXP, SEXP cSEXP, SEXP firstSEXP, SEXP lastSEXP, SEXP psSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c(cSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type last(lastSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type ps(psSEXP);
    rcpp_result_gen = Rcpp::wrap(ittotmat0_C(b, a, c, first, last, ps));
    return rcpp_result_gen;
END_RCPP
}
// E_booklets
arma::vec E_booklets(const arma::vec& b, const arma::ivec& a, arma::ivec& first, arma::ivec& last, arma::ivec& scoretab, const arma::ivec& n_score, const arma::ivec& nit);
RcppExport SEXP _dexter_E_booklets(SEXP bSEXP, SEXP aSEXP, SEXP firstSEXP, SEXP lastSEXP, SEXP scoretabSEXP, SEXP n_scoreSEXP, SEXP nitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type last(lastSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type scoretab(scoretabSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type n_score(n_scoreSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type nit(nitSEXP);
    rcpp_result_gen = Rcpp::wrap(E_booklets(b, a, first, last, scoretab, n_score, nit));
    return rcpp_result_gen;
END_RCPP
}
// NR_booklets
void NR_booklets(const arma::vec& b, const arma::ivec& a, arma::ivec& first, arma::ivec& last, arma::ivec& scoretab, const arma::ivec& n_score, const arma::ivec& nit, const int max_par_bk, arma::vec& EsufI, arma::mat& H);
RcppExport SEXP _dexter_NR_booklets(SEXP bSEXP, SEXP aSEXP, SEXP firstSEXP, SEXP lastSEXP, SEXP scoretabSEXP, SEXP n_scoreSEXP, SEXP nitSEXP, SEXP max_par_bkSEXP, SEXP EsufISEXP, SEXP HSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type last(lastSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type scoretab(scoretabSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type n_score(n_scoreSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type nit(nitSEXP);
    Rcpp::traits::input_parameter< const int >::type max_par_bk(max_par_bkSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type EsufI(EsufISEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type H(HSEXP);
    NR_booklets(b, a, first, last, scoretab, n_score, nit, max_par_bk, EsufI, H);
    return R_NilValue;
END_RCPP
}
// calibrate_Bayes_C
Rcpp::List calibrate_Bayes_C(const arma::ivec& a, const arma::ivec& first, const arma::ivec& last, const arma::ivec& ib, const arma::ivec& bi, const arma::ivec& nbi, const arma::ivec& nib, arma::ivec& bfirst, arma::ivec& blast, const arma::ivec& bmax, const arma::ivec& m, const arma::ivec& sufI, const arma::ivec& bkscoretab, const arma::vec& b_in, const arma::vec& fixed_b, const int from, const int step, const int ndraws, const double prior_eta, const double prior_rho, const int pgw);
RcppExport SEXP _dexter_calibrate_Bayes_C(SEXP aSEXP, SEXP firstSEXP, SEXP lastSEXP, SEXP ibSEXP, SEXP biSEXP, SEXP nbiSEXP, SEXP nibSEXP, SEXP bfirstSEXP, SEXP blastSEXP, SEXP bmaxSEXP, SEXP mSEXP, SEXP sufISEXP, SEXP bkscoretabSEXP, SEXP b_inSEXP, SEXP fixed_bSEXP, SEXP fromSEXP, SEXP stepSEXP, SEXP ndrawsSEXP, SEXP prior_etaSEXP, SEXP prior_rhoSEXP, SEXP pgwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::ivec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type last(lastSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type ib(ibSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type bi(biSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type nbi(nbiSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type nib(nibSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type bfirst(bfirstSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type blast(blastSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type bmax(bmaxSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type sufI(sufISEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type bkscoretab(bkscoretabSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b_in(b_inSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fixed_b(fixed_bSEXP);
    Rcpp::traits::input_parameter< const int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< const int >::type step(stepSEXP);
    Rcpp::traits::input_parameter< const int >::type ndraws(ndrawsSEXP);
    Rcpp::traits::input_parameter< const double >::type prior_eta(prior_etaSEXP);
    Rcpp::traits::input_parameter< const double >::type prior_rho(prior_rhoSEXP);
    Rcpp::traits::input_parameter< const int >::type pgw(pgwSEXP);
    rcpp_result_gen = Rcpp::wrap(calibrate_Bayes_C(a, first, last, ib, bi, nbi, nib, bfirst, blast, bmax, m, sufI, bkscoretab, b_in, fixed_b, from, step, ndraws, prior_eta, prior_rho, pgw));
    return rcpp_result_gen;
END_RCPP
}
// meanElSym
void meanElSym(const arma::vec& b, const arma::ivec& a, const arma::ivec& first, const arma::ivec& last, const int item1, const int item2, const int nI, const int mS, arma::vec& g);
RcppExport SEXP _dexter_meanElSym(SEXP bSEXP, SEXP aSEXP, SEXP firstSEXP, SEXP lastSEXP, SEXP item1SEXP, SEXP item2SEXP, SEXP nISEXP, SEXP mSSEXP, SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type last(lastSEXP);
    Rcpp::traits::input_parameter< const int >::type item1(item1SEXP);
    Rcpp::traits::input_parameter< const int >::type item2(item2SEXP);
    Rcpp::traits::input_parameter< const int >::type nI(nISEXP);
    Rcpp::traits::input_parameter< const int >::type mS(mSSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type g(gSEXP);
    meanElSym(b, a, first, last, item1, item2, nI, mS, g);
    return R_NilValue;
END_RCPP
}
// E_booklets_mean
arma::vec E_booklets_mean(const arma::vec& b, const arma::ivec& a, arma::ivec& first, arma::ivec& last, arma::ivec& scoretab, const arma::ivec& n_score, const arma::ivec& nit);
RcppExport SEXP _dexter_E_booklets_mean(SEXP bSEXP, SEXP aSEXP, SEXP firstSEXP, SEXP lastSEXP, SEXP scoretabSEXP, SEXP n_scoreSEXP, SEXP nitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type last(lastSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type scoretab(scoretabSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type n_score(n_scoreSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type nit(nitSEXP);
    rcpp_result_gen = Rcpp::wrap(E_booklets_mean(b, a, first, last, scoretab, n_score, nit));
    return rcpp_result_gen;
END_RCPP
}
// NR_booklets_mean
void NR_booklets_mean(const arma::vec& b, const arma::ivec& a, arma::ivec& first, arma::ivec& last, arma::ivec& scoretab, const arma::ivec& n_score, const arma::ivec& nit, const int max_par_bk, arma::vec& EsufI, arma::mat& H);
RcppExport SEXP _dexter_NR_booklets_mean(SEXP bSEXP, SEXP aSEXP, SEXP firstSEXP, SEXP lastSEXP, SEXP scoretabSEXP, SEXP n_scoreSEXP, SEXP nitSEXP, SEXP max_par_bkSEXP, SEXP EsufISEXP, SEXP HSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type last(lastSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type scoretab(scoretabSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type n_score(n_scoreSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type nit(nitSEXP);
    Rcpp::traits::input_parameter< const int >::type max_par_bk(max_par_bkSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type EsufI(EsufISEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type H(HSEXP);
    NR_booklets_mean(b, a, first, last, scoretab, n_score, nit, max_par_bk, EsufI, H);
    return R_NilValue;
END_RCPP
}
// ittotmat_C
arma::mat ittotmat_C(const arma::vec& b, const arma::ivec& a, const arma::vec& c, const arma::ivec& first, const arma::ivec& last, const arma::ivec& ps);
RcppExport SEXP _dexter_ittotmat_C(SEXP bSEXP, SEXP aSEXP, SEXP cSEXP, SEXP firstSEXP, SEXP lastSEXP, SEXP psSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c(cSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type last(lastSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type ps(psSEXP);
    rcpp_result_gen = Rcpp::wrap(ittotmat_C(b, a, c, first, last, ps));
    return rcpp_result_gen;
END_RCPP
}
// ss_table_enorm_C
arma::mat ss_table_enorm_C(const arma::ivec& a, const arma::vec& b, const arma::ivec& first, const arma::ivec& last, const arma::ivec& firstA, const arma::ivec& lastA, const arma::ivec& firstB, const arma::ivec& lastB);
RcppExport SEXP _dexter_ss_table_enorm_C(SEXP aSEXP, SEXP bSEXP, SEXP firstSEXP, SEXP lastSEXP, SEXP firstASEXP, SEXP lastASEXP, SEXP firstBSEXP, SEXP lastBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::ivec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type last(lastSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type firstA(firstASEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type lastA(lastASEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type firstB(firstBSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type lastB(lastBSEXP);
    rcpp_result_gen = Rcpp::wrap(ss_table_enorm_C(a, b, first, last, firstA, lastA, firstB, lastB));
    return rcpp_result_gen;
END_RCPP
}
// ss_table_im_C
arma::mat ss_table_im_C(const arma::ivec& a, const arma::vec& b, const arma::vec& c, const arma::ivec& first, const arma::ivec& last, const arma::ivec& firstA, const arma::ivec& lastA, const arma::ivec& firstB, const arma::ivec& lastB);
RcppExport SEXP _dexter_ss_table_im_C(SEXP aSEXP, SEXP bSEXP, SEXP cSEXP, SEXP firstSEXP, SEXP lastSEXP, SEXP firstASEXP, SEXP lastASEXP, SEXP firstBSEXP, SEXP lastBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::ivec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c(cSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type last(lastSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type firstA(firstASEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type lastA(lastASEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type firstB(firstBSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type lastB(lastBSEXP);
    rcpp_result_gen = Rcpp::wrap(ss_table_im_C(a, b, c, first, last, firstA, lastA, firstB, lastB));
    return rcpp_result_gen;
END_RCPP
}
// sampleNRM2_test
arma::ivec sampleNRM2_test(const arma::vec& theta, const arma::vec& b, const arma::ivec& a, const arma::ivec& first, const arma::ivec& last);
RcppExport SEXP _dexter_sampleNRM2_test(SEXP thetaSEXP, SEXP bSEXP, SEXP aSEXP, SEXP firstSEXP, SEXP lastSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type last(lastSEXP);
    rcpp_result_gen = Rcpp::wrap(sampleNRM2_test(theta, b, a, first, last));
    return rcpp_result_gen;
END_RCPP
}
// sampleNRM2_item
arma::imat sampleNRM2_item(const arma::vec& theta, const arma::vec& b, const arma::ivec& a, const arma::ivec& first, const arma::ivec& last);
RcppExport SEXP _dexter_sampleNRM2_item(SEXP thetaSEXP, SEXP bSEXP, SEXP aSEXP, SEXP firstSEXP, SEXP lastSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type last(lastSEXP);
    rcpp_result_gen = Rcpp::wrap(sampleNRM2_item(theta, b, a, first, last));
    return rcpp_result_gen;
END_RCPP
}
// Escore_C
arma::vec Escore_C(const arma::vec& theta, const arma::vec& b, const arma::ivec& a, const arma::ivec& first, const arma::ivec& last);
RcppExport SEXP _dexter_Escore_C(SEXP thetaSEXP, SEXP bSEXP, SEXP aSEXP, SEXP firstSEXP, SEXP lastSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type last(lastSEXP);
    rcpp_result_gen = Rcpp::wrap(Escore_C(theta, b, a, first, last));
    return rcpp_result_gen;
END_RCPP
}
// theta_mle_sec
arma::vec theta_mle_sec(const arma::vec& b, const arma::ivec& a, const arma::ivec& first, const arma::ivec& last);
RcppExport SEXP _dexter_theta_mle_sec(SEXP bSEXP, SEXP aSEXP, SEXP firstSEXP, SEXP lastSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type last(lastSEXP);
    rcpp_result_gen = Rcpp::wrap(theta_mle_sec(b, a, first, last));
    return rcpp_result_gen;
END_RCPP
}
// escore_wle
double escore_wle(const double theta, const arma::vec& b, const arma::ivec& a, const arma::ivec& first, const arma::ivec& last, const int nI, const int max_a);
RcppExport SEXP _dexter_escore_wle(SEXP thetaSEXP, SEXP bSEXP, SEXP aSEXP, SEXP firstSEXP, SEXP lastSEXP, SEXP nISEXP, SEXP max_aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type last(lastSEXP);
    Rcpp::traits::input_parameter< const int >::type nI(nISEXP);
    Rcpp::traits::input_parameter< const int >::type max_a(max_aSEXP);
    rcpp_result_gen = Rcpp::wrap(escore_wle(theta, b, a, first, last, nI, max_a));
    return rcpp_result_gen;
END_RCPP
}
// theta_wle_sec
arma::vec theta_wle_sec(const arma::vec& b, const arma::ivec& a, const arma::ivec& first, const arma::ivec& last);
RcppExport SEXP _dexter_theta_wle_sec(SEXP bSEXP, SEXP aSEXP, SEXP firstSEXP, SEXP lastSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type last(lastSEXP);
    rcpp_result_gen = Rcpp::wrap(theta_wle_sec(b, a, first, last));
    return rcpp_result_gen;
END_RCPP
}
// IJ_c
void IJ_c(const arma::vec& theta, const arma::vec& b, const arma::ivec& a, const arma::ivec& first, const arma::ivec& last, arma::mat& I, arma::mat& J, arma::vec& logFi);
RcppExport SEXP _dexter_IJ_c(SEXP thetaSEXP, SEXP bSEXP, SEXP aSEXP, SEXP firstSEXP, SEXP lastSEXP, SEXP ISEXP, SEXP JSEXP, SEXP logFiSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type last(lastSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type I(ISEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type J(JSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type logFi(logFiSEXP);
    IJ_c(theta, b, a, first, last, I, J, logFi);
    return R_NilValue;
END_RCPP
}
// PVrecycle
arma::vec PVrecycle(const arma::vec& b, const arma::ivec& a, const arma::ivec& first, const arma::ivec& last, const arma::vec& mu, const arma::vec& sigma, arma::ivec& scoretb, const arma::ivec& A, const double alpha);
RcppExport SEXP _dexter_PVrecycle(SEXP bSEXP, SEXP aSEXP, SEXP firstSEXP, SEXP lastSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP scoretbSEXP, SEXP ASEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type last(lastSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type scoretb(scoretbSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(PVrecycle(b, a, first, last, mu, sigma, scoretb, A, alpha));
    return rcpp_result_gen;
END_RCPP
}
// sampleIM
arma::imat sampleIM(const arma::vec& bIM, const arma::vec& cIM, const arma::ivec& a, const arma::ivec& first, const arma::ivec& last, const arma::ivec& scoretab);
RcppExport SEXP _dexter_sampleIM(SEXP bIMSEXP, SEXP cIMSEXP, SEXP aSEXP, SEXP firstSEXP, SEXP lastSEXP, SEXP scoretabSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type bIM(bIMSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type cIM(cIMSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type last(lastSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type scoretab(scoretabSEXP);
    rcpp_result_gen = Rcpp::wrap(sampleIM(bIM, cIM, a, first, last, scoretab));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dexter_fast_factor", (DL_FUNC) &_dexter_fast_factor, 2},
    {"_dexter_fast_factor_lev", (DL_FUNC) &_dexter_fast_factor_lev, 3},
    {"_dexter_ppoint", (DL_FUNC) &_dexter_ppoint, 1},
    {"_dexter_fill_resp_matrix", (DL_FUNC) &_dexter_fill_resp_matrix, 4},
    {"_dexter_ds_connected_groups", (DL_FUNC) &_dexter_ds_connected_groups, 1},
    {"_dexter_unequal_categories_C", (DL_FUNC) &_dexter_unequal_categories_C, 5},
    {"_dexter_make_booklets", (DL_FUNC) &_dexter_make_booklets, 6},
    {"_dexter_make_booklets_summed", (DL_FUNC) &_dexter_make_booklets_summed, 5},
    {"_dexter_make_booklets_summed_matrix", (DL_FUNC) &_dexter_make_booklets_summed_matrix, 3},
    {"_dexter_make_booklets_matrix", (DL_FUNC) &_dexter_make_booklets_matrix, 3},
    {"_dexter_mutate_booklet_score", (DL_FUNC) &_dexter_mutate_booklet_score, 3},
    {"_dexter_summarise_booklet_score", (DL_FUNC) &_dexter_summarise_booklet_score, 4},
    {"_dexter_merge_booklets", (DL_FUNC) &_dexter_merge_booklets, 4},
    {"_dexter_get_design_C", (DL_FUNC) &_dexter_get_design_C, 2},
    {"_dexter_polytomize_C", (DL_FUNC) &_dexter_polytomize_C, 7},
    {"_dexter_is_person_booklet_sorted", (DL_FUNC) &_dexter_is_person_booklet_sorted, 2},
    {"_dexter_parms_is_superset_matrix", (DL_FUNC) &_dexter_parms_is_superset_matrix, 4},
    {"_dexter_suf_stats_nrm", (DL_FUNC) &_dexter_suf_stats_nrm, 6},
    {"_dexter_suf_stats_im", (DL_FUNC) &_dexter_suf_stats_im, 5},
    {"_dexter_score_tab_single", (DL_FUNC) &_dexter_score_tab_single, 2},
    {"_dexter_tia_C", (DL_FUNC) &_dexter_tia_C, 9},
    {"_dexter_ElSym_C", (DL_FUNC) &_dexter_ElSym_C, 9},
    {"_dexter_possible_scores_C", (DL_FUNC) &_dexter_possible_scores_C, 3},
    {"_dexter_ittotmat0_C", (DL_FUNC) &_dexter_ittotmat0_C, 6},
    {"_dexter_E_booklets", (DL_FUNC) &_dexter_E_booklets, 7},
    {"_dexter_NR_booklets", (DL_FUNC) &_dexter_NR_booklets, 10},
    {"_dexter_calibrate_Bayes_C", (DL_FUNC) &_dexter_calibrate_Bayes_C, 21},
    {"_dexter_meanElSym", (DL_FUNC) &_dexter_meanElSym, 9},
    {"_dexter_E_booklets_mean", (DL_FUNC) &_dexter_E_booklets_mean, 7},
    {"_dexter_NR_booklets_mean", (DL_FUNC) &_dexter_NR_booklets_mean, 10},
    {"_dexter_ittotmat_C", (DL_FUNC) &_dexter_ittotmat_C, 6},
    {"_dexter_ss_table_enorm_C", (DL_FUNC) &_dexter_ss_table_enorm_C, 8},
    {"_dexter_ss_table_im_C", (DL_FUNC) &_dexter_ss_table_im_C, 9},
    {"_dexter_sampleNRM2_test", (DL_FUNC) &_dexter_sampleNRM2_test, 5},
    {"_dexter_sampleNRM2_item", (DL_FUNC) &_dexter_sampleNRM2_item, 5},
    {"_dexter_Escore_C", (DL_FUNC) &_dexter_Escore_C, 5},
    {"_dexter_theta_mle_sec", (DL_FUNC) &_dexter_theta_mle_sec, 4},
    {"_dexter_escore_wle", (DL_FUNC) &_dexter_escore_wle, 7},
    {"_dexter_theta_wle_sec", (DL_FUNC) &_dexter_theta_wle_sec, 4},
    {"_dexter_IJ_c", (DL_FUNC) &_dexter_IJ_c, 8},
    {"_dexter_PVrecycle", (DL_FUNC) &_dexter_PVrecycle, 9},
    {"_dexter_sampleIM", (DL_FUNC) &_dexter_sampleIM, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_dexter(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
