# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Escore_C <- function(theta, b, a, first, last) {
    .Call(`_dexter_Escore_C`, theta, b, a, first, last)
}

theta_mle_sec <- function(b, a, first, last) {
    .Call(`_dexter_theta_mle_sec`, b, a, first, last)
}

escore_wle <- function(theta, b, a, first, last, nI, max_a) {
    .Call(`_dexter_escore_wle`, theta, b, a, first, last, nI, max_a)
}

theta_wle_sec <- function(b, a, first, last) {
    .Call(`_dexter_theta_wle_sec`, b, a, first, last)
}

theta_EAP_GH_c <- function(p_score, theta, weights) {
    .Call(`_dexter_theta_EAP_GH_c`, p_score, theta, weights)
}

IJ_c <- function(theta, b, a, first, last, I, J, logFi) {
    invisible(.Call(`_dexter_IJ_c`, theta, b, a, first, last, I, J, logFi))
}

fast_factor <- function(x, as_int) {
    .Call(`_dexter_fast_factor`, x, as_int)
}

fast_factor_lev <- function(x, levs, as_int) {
    .Call(`_dexter_fast_factor_lev`, x, levs, as_int)
}

ppoint <- function(x) {
    .Call(`_dexter_ppoint`, x)
}

fill_resp_matrix <- function(person_id, item_id, item_score, out) {
    invisible(.Call(`_dexter_fill_resp_matrix`, person_id, item_id, item_score, out))
}

ds_connected_groups <- function(a) {
    .Call(`_dexter_ds_connected_groups`, a)
}

make_booklets <- function(person_id, item_id, item_score, booklet_id, booklet_score, merged) {
    .Call(`_dexter_make_booklets`, person_id, item_id, item_score, booklet_id, booklet_score, merged)
}

make_booklets_summed <- function(person_id, booklet_id, item_id, item_score, merged) {
    .Call(`_dexter_make_booklets_summed`, person_id, booklet_id, item_id, item_score, merged)
}

make_booklets_summed_matrix <- function(mtx, ncol, nrow) {
    .Call(`_dexter_make_booklets_summed_matrix`, mtx, ncol, nrow)
}

make_booklets_matrix <- function(mtx, ncol, nrow) {
    .Call(`_dexter_make_booklets_matrix`, mtx, ncol, nrow)
}

mutate_booklet_score <- function(person_id, booklet_id, item_score) {
    .Call(`_dexter_mutate_booklet_score`, person_id, booklet_id, item_score)
}

summarise_booklet_score <- function(person_id, booklet_id, item_id, item_score) {
    .Call(`_dexter_summarise_booklet_score`, person_id, booklet_id, item_id, item_score)
}

merge_booklets <- function(booklet_id, person_id, ds_booklet_id, maxb) {
    .Call(`_dexter_merge_booklets`, booklet_id, person_id, ds_booklet_id, maxb)
}

get_design_C <- function(booklet_id, item_id) {
    .Call(`_dexter_get_design_C`, booklet_id, item_id)
}

polytomize_C <- function(booklet_id, person_id, item_prop, item_score, booklet_score, nlev, nb) {
    .Call(`_dexter_polytomize_C`, booklet_id, person_id, item_prop, item_score, booklet_score, nlev, nb)
}

is_person_booklet_sorted <- function(booklet_id, person_id, ncores) {
    .Call(`_dexter_is_person_booklet_sorted`, booklet_id, person_id, ncores)
}

parms_is_superset_matrix <- function(x, item_id, item_score, maxs, ncores) {
    .Call(`_dexter_parms_is_superset_matrix`, x, item_id, item_score, maxs, ncores)
}

suf_stats_nrm <- function(booklet_id, booklet_score, item_id, item_score, nit, max_score) {
    .Call(`_dexter_suf_stats_nrm`, booklet_id, booklet_score, item_id, item_score, nit, max_score)
}

suf_stats_im <- function(booklet_score, item_id, item_score, nit, max_score) {
    .Call(`_dexter_suf_stats_im`, booklet_score, item_id, item_score, nit, max_score)
}

score_tab_single <- function(scores, max_score) {
    .Call(`_dexter_score_tab_single`, scores, max_score)
}

tia_C <- function(booklet_id, booklet_score, item_id, item_score, nb, nit, frst_item, ds_booklet_id, ds_item_id) {
    .Call(`_dexter_tia_C`, booklet_id, booklet_score, item_id, item_score, nb, nit, frst_item, ds_booklet_id, ds_item_id)
}

ElSym_C <- function(b, a, first, last, item1, item2, nI, mS, g) {
    invisible(.Call(`_dexter_ElSym_C`, b, a, first, last, item1, item2, nI, mS, g))
}

possible_scores_C <- function(a, first, last) {
    .Call(`_dexter_possible_scores_C`, a, first, last)
}

ittotmat0_C <- function(b, a, c, first, last, ps) {
    .Call(`_dexter_ittotmat0_C`, b, a, c, first, last, ps)
}

E_booklets <- function(b, a, first, last, scoretab, n_score, nit) {
    .Call(`_dexter_E_booklets`, b, a, first, last, scoretab, n_score, nit)
}

NR_booklets <- function(b, a, first, last, scoretab, n_score, nit, max_par_bk, EsufI, H) {
    invisible(.Call(`_dexter_NR_booklets`, b, a, first, last, scoretab, n_score, nit, max_par_bk, EsufI, H))
}

calibrate_Bayes_C <- function(a, first, last, ib, bi, nbi, nib, bfirst, blast, bmax, m, sufI, bkscoretab, b_in, fixed_b, from, step, ndraws, progress_init, prior_eta = 0.5, prior_rho = 0.5) {
    .Call(`_dexter_calibrate_Bayes_C`, a, first, last, ib, bi, nbi, nib, bfirst, blast, bmax, m, sufI, bkscoretab, b_in, fixed_b, from, step, ndraws, progress_init, prior_eta, prior_rho)
}

calibrate_Bayes_chains <- function(a, first, last, ib, bi, nbi, nib, bfirst, blast, bmax, m, sufI, bkscoretab, b_start, fixed_b, warmup, step, ndraws, progress_init, max_cores, prior_eta = 0.5, prior_rho = 0.5) {
    .Call(`_dexter_calibrate_Bayes_chains`, a, first, last, ib, bi, nbi, nib, bfirst, blast, bmax, m, sufI, bkscoretab, b_start, fixed_b, warmup, step, ndraws, progress_init, max_cores, prior_eta, prior_rho)
}

meanElSym <- function(b, a, first, last, item1, item2, nI, mS, g) {
    invisible(.Call(`_dexter_meanElSym`, b, a, first, last, item1, item2, nI, mS, g))
}

E_booklets_mean <- function(b, a, first, last, scoretab, n_score, nit) {
    .Call(`_dexter_E_booklets_mean`, b, a, first, last, scoretab, n_score, nit)
}

NR_booklets_mean <- function(b, a, first, last, scoretab, n_score, nit, max_par_bk, EsufI, H) {
    invisible(.Call(`_dexter_NR_booklets_mean`, b, a, first, last, scoretab, n_score, nit, max_par_bk, EsufI, H))
}

ittotmat_C <- function(b, a, c, first, last, ps) {
    .Call(`_dexter_ittotmat_C`, b, a, c, first, last, ps)
}

ss_table_enorm_C <- function(a, b, first, last, firstA, lastA, firstB, lastB) {
    .Call(`_dexter_ss_table_enorm_C`, a, b, first, last, firstA, lastA, firstB, lastB)
}

ss_table_im_C <- function(a, b, c, first, last, firstA, lastA, firstB, lastB) {
    .Call(`_dexter_ss_table_im_C`, a, b, c, first, last, firstA, lastA, firstB, lastB)
}

omp_ncores <- function() {
    .Call(`_dexter_omp_ncores`)
}

pv_chain_normal <- function(bmat, a, A, first, last, bk_cnit, bk_max_a, const_scoretab, scoretab_bk, scoretab_pop, scoretab_nscores, scoretab_np, mu_start, sigma_start, npv, progress_init, max_cores, warmup = 10L, step = 1L) {
    .Call(`_dexter_pv_chain_normal`, bmat, a, A, first, last, bk_cnit, bk_max_a, const_scoretab, scoretab_bk, scoretab_pop, scoretab_nscores, scoretab_np, mu_start, sigma_start, npv, progress_init, max_cores, warmup, step)
}

pv_chain_mix <- function(bmat, a, A, first, last, bk_cnit, bk_max_a, gscoretab, gscoretab_bk, gscoretab_nscores, gscoretab_np, mu_start, sigma_start, p_start, npv, progress_init, max_cores, warmup = 10L, step = 1L) {
    .Call(`_dexter_pv_chain_mix`, bmat, a, A, first, last, bk_cnit, bk_max_a, gscoretab, gscoretab_bk, gscoretab_nscores, gscoretab_np, mu_start, sigma_start, p_start, npv, progress_init, max_cores, warmup, step)
}

PV_sve <- function(b, a, bk_first, bk_last, bcni, booklet_id, booklet_score, mu, sigma, max_cores, pv_mat, pv_col_indx = 0L, niter = 1L) {
    invisible(.Call(`_dexter_PV_sve`, b, a, bk_first, bk_last, bcni, booklet_id, booklet_score, mu, sigma, max_cores, pv_mat, pv_col_indx, niter))
}

sampleNRM2_test <- function(theta, b, a, first, last) {
    .Call(`_dexter_sampleNRM2_test`, theta, b, a, first, last)
}

sampleNRM2_item <- function(theta, b, a, first, last) {
    .Call(`_dexter_sampleNRM2_item`, theta, b, a, first, last)
}

sampleIM <- function(bIM, cIM, a, first, last, scoretab) {
    .Call(`_dexter_sampleIM`, bIM, cIM, a, first, last, scoretab)
}

