# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Escore_C <- function(theta, b, a, first, last) {
    .Call(`_dexter_Escore_C`, theta, b, a, first, last)
}

theta_mle_sec <- function(b, a, first, last) {
    .Call(`_dexter_theta_mle_sec`, b, a, first, last)
}

escore_wle <- function(theta, b, a, first, last, nI, max_a) {
    .Call(`_dexter_escore_wle`, theta, b, a, first, last, nI, max_a)
}

theta_wle_sec <- function(b, a, first, last) {
    .Call(`_dexter_theta_wle_sec`, b, a, first, last)
}

theta_EAP_GH_c <- function(p_score, theta, weights) {
    .Call(`_dexter_theta_EAP_GH_c`, p_score, theta, weights)
}

IJ_c <- function(theta, b, a, first, last, I, J, logFi) {
    invisible(.Call(`_dexter_IJ_c`, theta, b, a, first, last, I, J, logFi))
}

fast_factor <- function(x, as_int) {
    .Call(`_dexter_fast_factor`, x, as_int)
}

fast_factor_lev <- function(x, levs, as_int) {
    .Call(`_dexter_fast_factor_lev`, x, levs, as_int)
}

fill_resp_matrix <- function(person_id, item_id, item_score, out) {
    invisible(.Call(`_dexter_fill_resp_matrix`, person_id, item_id, item_score, out))
}

ds_connected_groups <- function(a) {
    .Call(`_dexter_ds_connected_groups`, a)
}

make_booklets <- function(person_id, item_id, item_score, booklet_id, booklet_score, merged) {
    .Call(`_dexter_make_booklets`, person_id, item_id, item_score, booklet_id, booklet_score, merged)
}

make_booklets_summed <- function(person_id, booklet_id, item_id, item_score, merged) {
    .Call(`_dexter_make_booklets_summed`, person_id, booklet_id, item_id, item_score, merged)
}

make_booklets_summed_matrix <- function(mtx, ncol, nrow) {
    .Call(`_dexter_make_booklets_summed_matrix`, mtx, ncol, nrow)
}

make_booklets_matrix <- function(mtx, ncol, nrow) {
    .Call(`_dexter_make_booklets_matrix`, mtx, ncol, nrow)
}

mutate_booklet_score <- function(person_id, booklet_id, item_score) {
    .Call(`_dexter_mutate_booklet_score`, person_id, booklet_id, item_score)
}

summarise_booklet_score <- function(person_id, booklet_id, item_id, item_score) {
    .Call(`_dexter_summarise_booklet_score`, person_id, booklet_id, item_id, item_score)
}

merge_booklets <- function(booklet_id, person_id, ds_booklet_id, maxb) {
    .Call(`_dexter_merge_booklets`, booklet_id, person_id, ds_booklet_id, maxb)
}

get_design_C <- function(booklet_id, item_id) {
    .Call(`_dexter_get_design_C`, booklet_id, item_id)
}

polytomize_C <- function(booklet_id, person_id, item_prop, item_score, booklet_score, nlev, nb) {
    .Call(`_dexter_polytomize_C`, booklet_id, person_id, item_prop, item_score, booklet_score, nlev, nb)
}

is_person_booklet_sorted <- function(booklet_id, person_id, ncores) {
    .Call(`_dexter_is_person_booklet_sorted`, booklet_id, person_id, ncores)
}

parms_is_superset_matrix <- function(x, item_id, item_score, maxs, ncores) {
    .Call(`_dexter_parms_is_superset_matrix`, x, item_id, item_score, maxs, ncores)
}

suf_stats_nrm <- function(booklet_id, booklet_score, item_id, item_score, nit, max_score) {
    .Call(`_dexter_suf_stats_nrm`, booklet_id, booklet_score, item_id, item_score, nit, max_score)
}

suf_stats_im <- function(booklet_score, item_id, item_score, nit, max_score) {
    .Call(`_dexter_suf_stats_im`, booklet_score, item_id, item_score, nit, max_score)
}

score_tab_single <- function(scores, max_score) {
    .Call(`_dexter_score_tab_single`, scores, max_score)
}

tia_C <- function(booklet_id, booklet_score, item_id, item_score, nb, nit, frst_item, ds_booklet_id, ds_item_id) {
    .Call(`_dexter_tia_C`, booklet_id, booklet_score, item_id, item_score, nb, nit, frst_item, ds_booklet_id, ds_item_id)
}

elsymC <- function(b, a, first, last, omit_item = -1L) {
    .Call(`_dexter_elsymC`, b, a, first, last, omit_item)
}

list_elsymiC <- function(b, a, first, last) {
    .Call(`_dexter_list_elsymiC`, b, a, first, last)
}

possible_scores_C <- function(a, first, last) {
    .Call(`_dexter_possible_scores_C`, a, first, last)
}

ittotmatC <- function(b, a, c, first, last, ps) {
    .Call(`_dexter_ittotmatC`, b, a, c, first, last, ps)
}

sstable_nrmC <- function(a, b, firstA, lastA, firstB, lastB) {
    .Call(`_dexter_sstable_nrmC`, a, b, firstA, lastA, firstB, lastB)
}

sstable_imC <- function(a, b, c, firstA, lastA, firstB, lastB) {
    .Call(`_dexter_sstable_imC`, a, b, c, firstA, lastA, firstB, lastB)
}

elsym_binomC <- function(lbinom, b, a, first, last, omit_item = -1L) {
    .Call(`_dexter_elsym_binomC`, lbinom, b, a, first, last, omit_item)
}

list_elsymi_binomC <- function(lbinom, b, a, first, last) {
    .Call(`_dexter_list_elsymi_binomC`, lbinom, b, a, first, last)
}

Expect <- function(b, a, first, last, scoretab, n_score, nit) {
    .Call(`_dexter_Expect`, b, a, first, last, scoretab, n_score, nit)
}

Expect_binom <- function(lbinom, b, a, first, last, scoretab, n_score, nit) {
    .Call(`_dexter_Expect_binom`, lbinom, b, a, first, last, scoretab, n_score, nit)
}

Hess <- function(b, a, first, last, scoretab, n_score, nit, max_cores, E, H) {
    invisible(.Call(`_dexter_Hess`, b, a, first, last, scoretab, n_score, nit, max_cores, E, H))
}

Hess_binom <- function(lbinom, b, a, first, last, scoretab, n_score, nit, max_cores, E, H) {
    invisible(.Call(`_dexter_Hess_binom`, lbinom, b, a, first, last, scoretab, n_score, nit, max_cores, E, H))
}

calibrate_Bayes_chains <- function(a, first, last, ib, bi, nbi, nib, bfirst, blast, bmax, m, sufI, sufI_zero, bkscoretab, b_start, item_fixed, warmup, step, ndraws, progress_init, max_cores, prior_eta = 0.5, prior_rho = 0.5, prior_nu = 0.1) {
    .Call(`_dexter_calibrate_Bayes_chains`, a, first, last, ib, bi, nbi, nib, bfirst, blast, bmax, m, sufI, sufI_zero, bkscoretab, b_start, item_fixed, warmup, step, ndraws, progress_init, max_cores, prior_eta, prior_rho, prior_nu)
}

omp_ncores <- function() {
    .Call(`_dexter_omp_ncores`)
}

pv_chain_normal <- function(bmat, a, A, first, last, bk_cnit, bk_max_a, const_scoretab, scoretab_bk, scoretab_pop, scoretab_nscores, scoretab_np, mu_start, sigma_start, npv, progress_init, max_cores, warmup = 10L, step = 1L) {
    .Call(`_dexter_pv_chain_normal`, bmat, a, A, first, last, bk_cnit, bk_max_a, const_scoretab, scoretab_bk, scoretab_pop, scoretab_nscores, scoretab_np, mu_start, sigma_start, npv, progress_init, max_cores, warmup, step)
}

pv_chain_mix <- function(bmat, a, A, first, last, bk_cnit, bk_max_a, gscoretab, gscoretab_bk, gscoretab_nscores, gscoretab_np, mu_start, sigma_start, p_start, npv, progress_init, max_cores, warmup = 10L, step = 1L) {
    .Call(`_dexter_pv_chain_mix`, bmat, a, A, first, last, bk_cnit, bk_max_a, gscoretab, gscoretab_bk, gscoretab_nscores, gscoretab_np, mu_start, sigma_start, p_start, npv, progress_init, max_cores, warmup, step)
}

PV_sve <- function(b, a, bk_first, bk_last, bcni, booklet_id, booklet_score, mu, sigma, max_cores, pv_mat, pv_col_indx = 0L, niter = 1L) {
    invisible(.Call(`_dexter_PV_sve`, b, a, bk_first, bk_last, bcni, booklet_id, booklet_score, mu, sigma, max_cores, pv_mat, pv_col_indx, niter))
}

sampleNRM_testC <- function(theta, b, a, first, last) {
    .Call(`_dexter_sampleNRM_testC`, theta, b, a, first, last)
}

sampleNRM_itemC <- function(theta, b, a, first, last) {
    .Call(`_dexter_sampleNRM_itemC`, theta, b, a, first, last)
}

sampleIMC <- function(bIM, cIM, a, first, last, scoretab) {
    .Call(`_dexter_sampleIMC`, bIM, cIM, a, first, last, scoretab)
}

